version: "3"
services:
    api:
        build: 
            context: .
            dockerfile: Stackoverflow.API/DockerFile
        image: deboraj/stackoverflow.api
        env_file: 
            - Stackoverflow.API/web.env
        volumes:
            - stackoverflow-api-log:/app/Logs
        ports:
            - "6969:80"
            - "6008:443"
        entrypoint: ["dotnet", "Stackoverflow.API.dll"] 
        
        # Resource constraints
        mem_limit: 1g  # Limit memory usage to 1GB
        cpu_shares: 50  # Limit CPU usage to 50%

    web:
        build: 
            context: .
            dockerfile: Stackoverflow.Web/DockerFile
        image: deboraj/stackoverflow.web
        environment:   # Pass environment variables here
            DefaultStackoverflowConnection: "Server=sql.bsite.net\\MSSQL2016;Database=kartik_StackOverflow;User Id=kartik_StackOverflow;Password=hsn#2*#YW9Q%!M5;Trust Server Certificate=True;"
        
        env_file: 
            - Stackoverflow.Web/web.env
        volumes:
            - stackoverflow-web-log:/app/Logs
        ports:
            - "8080:80"
        entrypoint: ["dotnet", "Stackoverflow.Web.dll"]

        # Resource constraints
        mem_limit: 1g  # Limit memory usage to 1GB
        cpu_shares: 50  # Limit CPU usage to 50%
volumes:
    stackoverflow-api-log:
      external: true
    stackoverflow-web-log:
      external: true
     