version: "3"
services:
    api:
        build: 
            context: .
            dockerfile: Stackoverflow.API/DockerFile
        image: deboraj/stackoverflow.api
        env_file: 
            - Stackoverflow.API/web.env
        volumes:
            - stackoverflow-api-log:/app/Logs
        ports:
            - "8080:80"
        entrypoint: ["dotnet", "Stackoverflow.API.dll"]
volumes:
    stackoverflow-api-log:
      external: true
     