version: "3"
services:
    api:
        build: 
            context: .
            dockerfile: Stackoverflow.API/DockerFile
        image: deboraj/stackoverflow.api
        env_file: 
            - Stackoverflow.API/web.env
        volumes:
            - stackoverflow-api-log:/app/Logs
        ports:
            - "6969:80"
            - "6008:443"
        entrypoint: ["dotnet", "Stackoverflow.API.dll"]

    web:
        build: 
            context: .
            dockerfile: Stackoverflow.Web/DockerFile
        image: deboraj/stackoverflow.web
        env_file: 
            - Stackoverflow.Web/web.env
        volumes:
            - stackoverflow-web-log:/app/Logs
        ports:
            - "8080:80"
        entrypoint: ["dotnet", "Stackoverflow.Web.dll"]
volumes:
    stackoverflow-api-log:
      external: true
    stackoverflow-web-log:
      external: true
     